### ISSUE TITLE
integrating in UWP ffmpeg build

### ISSUE THREAD

**Issue by ispysoftware** [ShiftMediaProject/libvpx#3] opened 2019-01-02 08:53 UTC
First of all thanks a lot for this.
Do you have any idea about how to use this in a UWP build of ffmpeg?

https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT

- that comes with bare bones decoders and basically no encoders. It would be great to add libvpx to it but nothing i'm trying seems to work. The build command I'm using is:

`../../../configure \
--toolchain=msvc \
--disable-programs \
--disable-d3d11va \
--disable-dxva2 \
--disable-opencl \
--arch=x86_64 \
--enable-shared \
--enable-libvpx \
--enable-cross-compile \
--target-os=win32 \
--extra-cflags="-MD -DWINAPI_FAMILY=WINAPI_FAMILY_APP -D_WIN32_WINNT=0x0A00 -I/d/ffmpeg-src/libvpx/include" \
--extra-ldflags="-APPCONTAINER WindowsApp.lib libvpx.lib -L/d/ffmpeg-src/libvpx/lib/x64" \
--prefix=../../../Build/Windows10/x64`

just gives me

`C compiler test failed.`

(excluding the libvpx stuff it builds ok)

Are the releases built for UWP or is that something I need to do myself? Do you have any ideas on how to get ffmpeg to link it in? Thanks.

**Comment by ispysoftware** [comment] 2019-01-02 22:00
Yeah I built libvpx_winrt.lib but when I try to link it into the UWP ffmpeg build I still get a compiler error
`C compiler test failed`
I'm not entirely sure about what i'm doing though - i'm more of a c# developer, this yasm/mingw/nasm/msys2 stuff is all new to me. Have you managed to get a working UWP ffmpeg build with any external libraries included? Do you have an ETA on the UWP platform? I'd happily contribute some $ to get this happening.

**Comment by Sibras** [comment] 2019-01-03 02:46
> 
> Have you managed to get a working UWP ffmpeg build with any external libraries included? Do you have an ETA on the UWP platform? I'd happily contribute some $ to get this happening.

No ETA at present (although it potentially could be done sooner rather than later) as it depends on how I prioritise stuff. Of course donations are always welcome (theres a link on the repo landing page) as I admit it does make good motivation to get stuff done. I can probably look at just selectively generating project dependencies with the FFVS project generator so that the currently unsupported dependencies are just ignored, which would be the fastest way of getting it up and running.

**Comment by ispysoftware** [comment] 2019-01-03 02:57
i couldn't find a donate link, could you direct me?

**Comment by Sibras** [comment] 2019-01-03 03:06
Its the badge on the github front page ([link](https://shiftmediaproject.github.io/8-donate/)). I guess i didnt make it it visible enough.

**Comment by ispysoftware** [comment] 2019-01-03 03:08
got it - sorry i was looking at a different page

**Comment by Sibras** [comment] 2019-01-03 03:14
thanks

**Comment by Sibras** [comment] 2019-01-07 19:01
OK, So I have updated [FFVS Project Generator](https://github.com/ShiftMediaProject/FFVS-Project-Generator) to now be able to generate WinRT/UWP configurations. So feel free to test if it works for you.
Youll have to build from source for the moment until ive had more time to test it, but i was able to get a FFmpeg project to work using:
`project_generate.exe --enable-libvpx`
So give that a try and let me know how it works for you

**Comment by Sibras** [comment] 2019-01-09 12:39
Hmm , sorry i did a rebase and things got messed. Try force pulling the latest version now.
The GetProcessAffinityMask error is because that was added only in win10 sdk 10.0.16299. The config file auto detects that and "now" disables that when using an older sdk.

For convenience I will point out that FFVS generates a file called "ffmpeg_with_latest_sdk.bat" that if run will open the solution using the latest sdk detected on the host system.

**Comment by ispysoftware** [comment] 2019-01-09 13:20
Thanks - I force pulled FFVS, regenerated the solution (running project_generate.exe --enable-libvpx), ran the latest_sdk.bat file and avutil builds fine so I built the solution and got 2 errors:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	ff_flac_enc_lpc_16_sse4 already defined in dce_defs.obj	libavcodec	D:\ffmpeg-src\source\FFmpeg\SMP\flac_dsp_gpl.obj	1	
Error	LNK1169	one or more multiply defined symbols found	libavcodec	D:\ffmpeg-src\msvc\bin\x64\avcodecd_winrt.dll	1	
`

**Comment by Sibras** [comment] 2019-01-09 14:02
I compiled that exact configuration on my pc and didnt get any errors (i only checked 32bit), sure enough change to x64 and i can reproduce.

Interestingly from the error line it seems like your nasm install is not working correctly as there shouldn't be a obj file in at "D:\ffmpeg-src\source\FFmpeg\SMP\flac_dsp_gpl.obj" (unless you changed the intermediate directory) as it should be in "D:\ffmpeg-src\source\FFmpeg\SMP\obj\DebugDLLWinRT\x64\libavcodec\x86\flac_dsp_gpl.obj"

Not that this should affect the ability to build. For the moment the solution is to change your configure line to enable gpl:

`project_generate.exe --enable-gpl --enable-version3 --enable-libvpx`

**Comment by Sibras** [comment] 2019-01-09 14:46
Pushed a fix for the non-gpl case.

**Comment by ispysoftware** [comment] 2019-01-10 00:43
I'm still getting the same error with the non-GPL build. There isn't a file at 
`D:\ffmpeg-src\source\FFmpeg\SMP\flac_dsp_gpl.obj`
- i'm not sure where it's getting that path from, all the .obj files are where they should be..
`d:\ffmpeg-src\source\ffmpeg\smp\obj\debugdllwinrt\x64`

calling 

`project_generate.exe --enable-gpl --enable-version3 --enable-libvpx`
that does build successfully - unfortunately a gpl build isn't an option

**Comment by Sibras** [comment] 2019-01-10 03:08
I cant reproduce this at all on my end. When generating a new project with just "--enable-libvpx" the input file "libavcodec\x86\flac_dsp_gpl.asm" is no longer included in the project when using the latest FFVS. Can you confirm that your project file does not include this asm file.

**Comment by Sibras** [comment] 2019-01-10 05:03
Check to make sure that your FFVS code matches the latest version found at [repo](https://github.com/ShiftMediaProject/FFVS-Project-Generator/commit/5de045eadfce030f01b3e622db67061cd191d02b).

I didnt do any forced pushes or anything but make sure that they match.

**Comment by ispysoftware** [comment] 2019-01-10 05:20
Sorry, my fault, I forgot to rebuild the ffvs project before running the executable. It's working - thanks so much for this, I really appreciate it. And thanks for getting it done so quickly as well.

There are a few warnings, like:
`Severity	Code	Description	Project	File	Line	Suppression State
Warning	RC4002	too many actual parameters for macro 'av_alloc_size'	libpostproc	D:\ffmpeg-src\source\FFmpeg\libavutil\mem.h	220	
`
- do you know if that will be an issue?

also, when including libpx - do I need to include the libvpx_winrt.dll file or is it packaged into the avcodec_winrt.dll automagically?

**Comment by Sibras** [comment] 2019-01-10 05:41
The warnings are not an issue. These are from ffmpeg code which has been like that for ages without issue.

As for libvpx.dll. If your just using the vpx functionality directly through ffmpeg then all you need is the avcodec_winrt.dll to be linked to your software. However you will need to distribute the libvpx_winrt.dll as it will be needed at run time (unless you compile using DLLStaticDeps configuration in which case all you need to distribute is the ffmpeg dll)

**Comment by ispysoftware** [comment] 2019-01-10 10:50
I dunno if it's of interest to you or not but the bindings generated with
https://github.com/Ruslan-B/FFmpeg.AutoGen
(with some changes to the way it loads libraries and updates to the naming conventions)
seem to work fine with these winrt uwp generated ffmpeg dlls - making ffmpeg nearly fully accessible from c# in uwp projects. 
Awesome work Mat.

**Closed** 2019-01-14 16:00 UTC
